### ISSUE TITLE
Unable to compile on OS X

### ISSUE THREAD

**Issue by jah2488** [christopherpow/nesicide#10]
Hey, so I installed the `Qscintilla2` package before attempting to compile, but ran into an error. Any ideas?

````
make -C apps/nes-emulator
make[1]: *** No rule to make target `Resources/controller.icns', needed by `release/nes-emulator.app/Contents/Resources/controller.icns'.  Stop.
make: *** [apps/nes-emulator/nes-emulator] Error 2
````

**Comment by christopherpow** [comment]
If you download the OSX-updated deps package that has the WINE headers in it now.

It is here:
https://sites.google.com/site/nesicideproject/documents/deps.tar.bz2?attredirects=0&d=1
