### ISSUE TITLE
Include deps/ folder

### ISSUE THREAD

**Issue by nbrookie** [christopherpow/nesicide#16]
Hey Nesicide devs,

I am trying to compile Nesicide on OSX. I followed the other issues, mainly this one https://github.com/christopherpow/nesicide/issues/8, and was able to compile to a point, but I am getting these 4 errors now:
```
winuser.h:4017:55: error: unknown type name '__builtin_ms_va_list'; did you mean '__builtin_va_list'?
winuser.h:4018:57: error: unknown type name '__builtin_ms_va_list'; did you mean '__builtin_va_list'?
winbase.h:1666:85: error: unknown type name '__builtin_ms_va_list'; did you mean '__builtin_va_list'?
winbase.h:1665:84: error: unknown type name '__builtin_ms_va_list'; did you mean '__builtin_va_list'?
```

What I have mainly done is symlink all the wine headers into the `common/` directory. This was a hack to try to get things working, and seems to be biting me. 

In trying to find another way, I noticed that in a couple of Makefiles there is a reference to a `../../deps/osx` folder that has the wine headers in it, the SDL headers in it, and a file called `stdafxhack`. There may be other files in there but these are the ones that I have noticed thus far. 

Is there any possibility that you can cut an `osx` branch or something similar, and include all osx files in there just for reference?

Thanks in advance!

**Comment by christopherpow** [comment]
I've uploaded the deps package here:
https://sites.google.com/site/nesicideproject/documents/deps.tar.bz2?attredirects=0&d=1
