### ISSUE TITLE
Trouble 'make'-ing on Mac OS X

### ISSUE THREAD

**Issue by aguerrero810** [christopherpow/nesicide#18]
I get lots of these errors:

    ( cd ../../deps/rtmidi; qmake; make )
    /bin/sh: line 0: cd: ../../deps/rtmidi: No such file or directory
    WARNING: /Users/anthony/Desktop/nesFCStuff/nesicide-master/libs/famitracker/famitracker-lib.pro:74: Unescaped backslashes are deprecated.

When using `make`.

**Comment by christopherpow** [comment]
Download and extract this package: https://drive.google.com/file/d/0BwhBNo66Kd6bUXhsOUtrM1lndUU/view?usp=sharing
into your nesicide directory. Looks like you have an outdated deps package that doesn't include rtmidi. The above link does.

**Comment by aguerrero810** [comment]
I may be missing something, as now I get
`/Applications/Xcode.app/Contents/Developer/usr/bin/make -C libs/famitracker
make[1]: *** No rule to make target 'rtmidi', needed by 'release/libfamitracker.1.0.0.dylib'.  Stop.`
