### ISSUE TITLE
Delete autogenerated makefiles in "clean.sh"?

### ISSUE THREAD

**Issue by jimbo1qaz** [christopherpow/nesicide#27]
I had an issue where famitracker-lib was unable to find SDL because build/../libs/famitracker/famitracker-lib.pro (which isn't directly referenced from build.sh or clean.sh) generated an invalid Makefile when I didn't have libsdl1.2-dev installed. Running clean.sh would not solve this issue.

Adding `find .. -name 'Makefile.*' -exec rm {} ';'` to clean.sh would solve this issue. Does `qmake clean` or something of that sort exist, and does it work for files located that far away from build/?

EDIT: This command accidentally erases common/resources/Makefile.template :(

**Comment by christopherpow** [comment]
Fixed in https://github.com/christopherpow/nesicide/commit/5d38b807313b4c93d7bfa3db4558d3bc0579ac5b
