### ISSUE TITLE
Terminal=true needs to be removed from the desktop file

### ISSUE THREAD

**Issue by probonopd** [christopherpow/nesicide#30]
When launching the application from https://knob.phreneticappsllc.com/nesicide/nesicide-x86_64.AppImage though its desktop file, then a terminal is opened with output like this:

![](https://raw.githubusercontent.com/AppImage/appimage.github.io/b404ce2cb268dc9caba1e609a5b7d7b153f919b8/database/nesicide/screenshot.png)

Assuming this is a GUI application, `Terminal=true` needs to be removed from the desktop file.

Reference: https://github.com/AppImage/appimage.github.io/pull/131

**Comment by christopherpow** [comment]
Fixed in https://github.com/christopherpow/nesicide/commit/ae215d91b50a13ba3236d95b7297d84435faf2a0
