### ISSUE TITLE
Reduce output of the Travis CI scripts

### ISSUE THREAD

**Issue by rogersachan** [christopherpow/nesicide#31]
Currently, there is no way to tell what went wrong with the Travis CI builds without downloading the logs. There should be some way to silence the current build script to only give off warnings and errors.

**Comment by christopherpow** [comment]
I agree, but I'm new to the whole Travis thing and don't have much time to devote to figuring it out. Currently I believe the build is failing because of some Qt incompatibilities within the Travis environment.

**Comment by christopherpow** [comment]
Travis builds for Linux and OSX are passing now. Travis builds for Windows builds is in progress, not working yet [for Travis community...]. I'm closing this. I will continue to look to reduce log clutter.
