### ISSUE TITLE
Famitracker on Mac uses 100% CPU.

### ISSUE THREAD

**Issue by slembcke** [christopherpow/nesicide#37]
I sampled the process and found that it's repainting it's UI constantly. Not great for running on battery power with the fans blasting. Haven't tried reproducing the issue on Linux yet.

I was hoping that a fix would be as simple as adding a sleep call somewhere for a few milliseconds, but I've never worked on a Qt project before and am still in the process of getting the dev tools working.

**Comment by slembcke** [comment]
The timestamp on the Famitracker app bundle was less than an hour ago, though it still uses 100% CPU. I kind of gave up trying to get the Qt tools working the other day so I'm not much help unfortunately. :-\

**Comment by christopherpow** [comment]
Closing as duplicate of issue #60 which will be closed shortly.
