### ISSUE TITLE
rc2qt.py missing imports (and setup directions)

### ISSUE THREAD

**Issue by jimbo1qaz** [christopherpow/nesicide#38]
I'm taking another stab at [porting j0CC to Qt](url). I checked vanilla and nesicide into a Git repo, ran (dos2unix, lowercase all file names, strip comments and blank lines, clang-format) and wrote a diff summary at https://hackmd.io/@IFuHNFVvQXWfCLfmOaJA1w/S1L_6G71S .

The issue is, I cannot get rc2qt.py's imports to work.

```
from antlr4 import *
from rcLexer import rcLexer
from rcVisitor import rcVisitor
from rcParser import rcParser
```

- rc2qt is Python 2 only, looking at the print syntax.
- `pip install antlr4-python2-runtime`
- `rcLexer/Visitor/Parser` are missing from your Git repo, and I cannot find them online, so I cannot use this script.
    - https://github.com/christopherpow/nesicide/blob/5639281fc50bc3a7a29516a64eef1fc0b7f120f4/.gitignore#L37-L40 why did you put them in your .gitignore :joy:

If you want to use a build system to allow reproducible Python dependency installs, I have experience using https://poetry.eustace.io/. You could declare "Python 2, antlr4-python2-runtime required, whatever other packages, etc".

**Comment by jimbo1qaz** [comment]
Almost-working instructions:

- `pip install antlr4-python2-runtime`
- `sudo apt install antlr4`
- in dir: `antlr4 -Dlanguage=Python2 rc.g4`

>`warning(184): rc.g4:142:0: One of the token ACCELERATOR_OPTIONS values unreachable. CONTROL is always overlapped by token CONTROL`

The issue is, antlr4 generates rcListener.py and not rcVisitor.py.

antlr3 does not generate the warning(184) but also fails to generate rcVisitor.py.

**Comment by jimbo1qaz** [comment]
In master, you removed `sys.setdefaultencoding('utf8')`. I'm not sure that's a good idea, I don't know the impacts, but apparently Python used to open files on Windows in a non-utf8 locale.

https://stackoverflow.com/a/42070962

> PEP 529: Change Windows filesystem encoding to UTF-8
> PEP 528: Change Windows console encoding to UTF-8
> 
> But the default encoding for open() is still whatever Python manages to infer from the environment.

PEP 529 changes paths. PEP 528 changes console IO. Neither changes open() encodings.

**Comment by christopherpow** [comment]
That appears to have been true in Python2, but the function is not available in Python3 and default encoding is utf8.
