### ISSUE TITLE
Tooltips break scrolling

### ISSUE THREAD

**Issue by norill** [christopherpow/nesicide#46]
1. mouseover an instruction in editor window
2. wait for a tooltip to appear
3. mouseover the tooltip, it should disappear
4. mouse wheel scrolling is broken now. moving the mouse out from the editor fixes it.

Windows 7

**Comment by christopherpow** [comment]
I am unable to reproduce this in OSX. I don't have Win7. It could be an issue with QScintilla, or with how the tooltip gives up focus. I'll have to find a Win7 VM.

**Comment by norill** [comment]
looks fixed in some newer version
