### ISSUE TITLE
Buggy newlines on Windows

### ISSUE THREAD

**Issue by norill** [christopherpow/nesicide#47]
The setting Code Editor -> Whitespace -> EOL is buggy on Windows. Using "Windows (CR+LF)" results in 0D 0D 0A being written to files. "Linux (LF)" results in 0D 0A. Looks like it's using text mode instead of binary mode when writing files. Also, changing settings crashes IDE, fortunately they get saved before crashing.

**Comment by aa-dav** [comment]
Issue still exists. (windows 10, last build) 
Broken 0D 0D 0A newlines could be seen in uploaded archive with project in my new issue here: https://github.com/christopherpow/nesicide/issues/55
Note, that they are not visible in the IDE itself during regular work, but they are definitely related to strange new-line-behaviour described in the issue mentioned (if there are no 0D 0Ds lines are not doubled in new tabs of debugging bug).
Also they could be seen in hex editor or show themselves if you copy text to Notepad++.
I think reason is not in the "using text mode while saving text". 

I made first experiment:
1. Environment Settings for End-of-Line (EOL) are:
- CR+LF
- "Force consistence on save/load" IS OFF (IDE is reloaded to apply settings without doubts)
2. Project has file with 0A (LF) as EOL (utils.inc)
3. Open it and add one new line in the middle and Save
4. All EOLs are converted to 0D+0A, but new one is 0D+0D+0A.
5. Open it again and add new one line somethere else and Save
6. Wrong EOL from previous step has dissapeared, but new one is 0D0D0A again
7. Write new lines chaotically - then Save
8. Random 0D0D0A exist in file with correct ones 0D0A. Seems like some dissapears after save, but more you edit more of them persist.

Second test right now:
1. Change Settings for End-of-Line (EOL) to:
- LF (Unix)
- "Force consistence on save/load" to ON (IDE is reloaded to apply settings without doubts)
Open previous file (with a lot of 0D0D0A), change 1 symbol and Save:
2. All EOL becomes 0D0A (CRLF)

Seems like "LF+force consistence" works as CRLF on WIndows. Anyway it seems strange.

**Comment by christopherpow** [comment]
Can you please try this once more, I removed some code that might have been interfering with EOL translations. I don't have Windows available at the moment to check.

**Comment by norill** [comment]
i can't find the latest windows build

**Comment by christopherpow** [comment]
https://bintray.com/christopherpow/nesicide/nesicide/1.0.103#files

**Comment by norill** [comment]
looks fixed
