### ISSUE TITLE
Outdated Qt link in README

### ISSUE THREAD

**Issue by spacekitcat** [christopherpow/nesicide#48]
I noticed that the link to Qt 5.6.2 in the Readme no longer works, I think you really want to link to https://download.qt.io/archive/qt/5.6/5.6.2/ 

I could raise a PR for it if you'd like.

**Comment by christopherpow** [comment]
go ahead and pr thanks

**Comment by christopherpow** [comment]
Closing as OBE -- link updated to Qt 5.12.6.
