### ISSUE TITLE
Website AppImage problem

### ISSUE THREAD

**Issue by electronoob** [christopherpow/nesicide#52]
Are the appimage downloads here supported here on github issues?
https://knob.phreneticappsllc.com/nesicide/?s=download

**Comment by christopherpow** [comment]
What support do you need? I am not able to test on native Linux.

**Comment by electronoob** [comment]
okay, might not be able to help me but i appreciate you taking a look.

using: nesicide-0886982-x86_64.AppImage
on manjaro linux.

when i try to compile one of the example templates i get various errors and unable to compile.

**asm template**
Project build started.
Building: obj/nes/hello_world.chr
Constructing 'bank0':
   Adding: tilesets/titlegfx.png(4096 bytes)
   Adding: tilesets/gamegfx.png(4096 bytes)
Building: obj/nes/hello_world.prg
make -f nesicide.mk all
ca65 -t nes -g --debug-info -I . -o obj/nes/main.o src/main.s
ca65 -t nes -g --debug-info -I . -o obj/nes/header.o header.s
cl65 -t nes -C nes.ini -Wl --dbgfile,hello_world.dbg obj/nes/main.o obj/nes/header.o -o obj/nes/hello_world.prg 
ld65: Error: Input file 'nes.lib' not found
make: *** [nesicide.mk:147: obj/nes/hello_world.prg] Error 1
Build failed while processing Source.






**UC template**
Project build started.
Building: obj/nes/untitled3.prg
make -f nesicide.mk all
ca65 -t nes -g --debug-info -I . -o obj/nes/crt0.o lib/crt0.s
ca65 -t nes -g --debug-info -I . -o obj/nes/header.o header.s
java -jar /tmp/.mount_nesiciT6TZFL/cc65/../uc65-release-0.5-rc4/uc65.jar -i src -o obj/nes/data.s source/data.uc
Error: Unable to access jarfile /tmp/.mount_nesiciT6TZFL/cc65/../uc65-release-0.5-rc4/uc65.jar
make: *** [uc.mk:6: obj/nes/data.o] Error 1
Build failed while processing Source.





**C template**
Project build started.
Building: obj/nes/hello_world.chr
Constructing 'bank0':
   Adding: tilesets/titlegfx.png(4096 bytes)
   Adding: tilesets/gamegfx.png(4096 bytes)
Building: obj/nes/hello_world.prg
make -f nesicide.mk all
cl65 --create-dep obj/nes/main.d -S -t nes -g --debug-info -I . -o obj/nes/main.s src/main.c
ca65 -t nes -g --debug-info -I . -o obj/nes/main.o obj/nes/main.s
obj/nes/main.s(12): Error: Cannot open include file 'longbranch.mac': No such file or directory
obj/nes/main.s(57): Error: ':' expected
src/main.c(15): Note: Assembly code generated from this line
obj/nes/main.s(57): Error: Unexpected trailing garbage characters
src/main.c(15): Note: Assembly code generated from this line
obj/nes/main.s(119): Error: ':' expected
src/main.c(38): Note: Assembly code generated from this line
obj/nes/main.s(119): Error: Unexpected trailing garbage characters
src/main.c(38): Note: Assembly code generated from this line
obj/nes/main.s(179): Error: Symbol 'jne' is already defined
src/main.c(50): Note: Assembly code generated from this line
obj/nes/main.s(179): Error: ':' expected
src/main.c(50): Note: Assembly code generated from this line
obj/nes/main.s(179): Error: Symbol '.size' is already defined
src/main.c(50): Note: Assembly code generated from this line
obj/nes/main.s(179): Error: Unexpected trailing garbage characters
src/main.c(50): Note: Assembly code generated from this line
make: *** [nesicide.mk:111: obj/nes/main.o] Error 1
Build failed while processing Source.

**Comment by christopherpow** [comment]
I've replicated in my Ubuntu VM. I'll take a look.

**Comment by electronoob** [comment]
thank you for the update

**Comment by christopherpow** [comment]
Please try build 23f147b. It works in my Ubuntu VM.

**Comment by electronoob** [comment]
much better! thank you for taking care of that issue.

**Comment by christopherpow** [comment]
No problem. Sorry for the inconvenience. I don't get much time to work on this these days, and with three platforms it gets a bit hairy. Bug reports always welcome...
