### ISSUE TITLE
Debugging macro from another unit

### ISSUE THREAD

**Issue by aa-dav** [christopherpow/nesicide#55]
(Windows 10, latest build)
If I enter in the debug mode and step through code (by F8 key) and reach macro which resides in another file (let's suppose, "utils.inc") IDE opens up 3 tabs with this file (utils.inc) and can't show current instruction pointer at all. Every step through macro instructions will open new 3 tabs of the same code and does nothing more. Issue doesn't exist if macro resides in current file or we don't go step-by-step through macro (plain code works well). 
Another symptom: tabs opened in this way looks like all new lines are doubled - new empty lines after each original line.
Maybe it's relevant: all files reside in the subfolder "src" of project like in template.

**Comment by christopherpow** [comment]
Can you provide a minimal project that shows this issue? Thanks.

**Comment by aa-dav** [comment]
Here it is:
[Test02.zip](https://github.com/christopherpow/nesicide/files/4137329/Test02.zip)
Note that is location on my hard drive is c:\devel\nes\Test02 (root folder of project)
main.s contains entry point and macro some1
utils.inc contains macro some2
entry point in main.s uses macros at start and then some2 is reached mess with tabs appears.
Hope it helps. Thanks.

**Comment by christopherpow** [comment]
I'm finally getting back to this.

**Comment by christopherpow** [comment]
Fix for this will be in build today.
