### ISSUE TITLE
Ignoring newly created source file destroys project file .nesproject

### ISSUE THREAD

**Issue by aa-dav** [christopherpow/nesicide#59]
(Windows 10, last build)
Let's create new source file in project tree, name it like "some.s" and press "Ok". It appears in tabs, but not in filesystem yet. Now, if you close IDE making no changes in empty new file then IDE will kill .project file - it will be empty and project could not be opened anymore. You have to recreate it.
There is no such behaviour if you add some lines in file and save it before exiting IDE, but IDE do not save it until it was changed - and it is not marked as changed after creation.

**Comment by christopherpow** [comment]
Thanks. I have seen the project file destruction before but not been able to link it to anything in particular. I'll try to reproduce it this way.

**Comment by christopherpow** [comment]
I've fixed this. Build coming.

**Comment by aa-dav** [comment]
Build from your email fixes this.
