### ISSUE TITLE
100% CPU usage on Windows

### ISSUE THREAD

**Issue by norill** [christopherpow/nesicide#60]
Nesicide V2.0.0 uses 100% CPU at all times, it didnt occur with Nesicide V1.007

**Comment by aa-dav** [comment]
Indeed, nesicide.exe consumes all time of one CPU core even while emulator is stopped.

**Comment by christopherpow** [comment]
I have root caused this to my Qt Famitracker library which is included in nesicide. I don't yet have a fix, short of removing it.

**Comment by christopherpow** [comment]
This is a duplicate of https://github.com/christopherpow/nesicide/issues/37

**Comment by christopherpow** [comment]
Commit 89d4399bfe44869ccdd1a0510d16eee214bcc16a fixes this.
