### ISSUE TITLE
Cannot delete music from project tree

### ISSUE THREAD

**Issue by aa-dav** [christopherpow/nesicide#62]
If I add existing music file (*.ftm) into sounds\musics in the project tree then I cannot remove it from IDE. "Delete music file" just do nothing. Need to edit .project file manually to remove it.

By the way - are ftm files somehow integrated into build chain or we can add them in project for editing only?

**Comment by christopherpow** [comment]
The goal is to have the FTM module exporter run as part of the build process. I haven't got there yet, so for now it's just part of the IDE for editing.

**Comment by aa-dav** [comment]
It helps already in my case because I choose FamiTone2 library by Shiru and it requires to use FamiTracker export functions. And as far as FamiTracker is integrated in IDE it is easy to complete this things.

**Comment by christopherpow** [comment]
I have a fix for the issue as stated (deletion of music files) in the latest build. However, there seem to be some stability issues crept into Windows builds. I am looking into that.

**Comment by aa-dav** [comment]
Yes, stability of last build seems ok. And debugging macro from another units looks great.

**Comment by christopherpow** [comment]
![image](https://user-images.githubusercontent.com/1640688/76523284-2598bd80-6436-11ea-9cf5-43568fb54a82.png)
For me it looks like there's extra newlines. Does it look like this for you? I'm thinking it's the encoding.

**Comment by aa-dav** [comment]
Yes, extra new lines are still issue. But I wrote utility to automatically remove them in all subfolders of current folder and use it then meet some problems. 
[0D0D0Afixer.zip](https://github.com/christopherpow/nesicide/files/4328547/0D0D0Afixer.zip)
Usually you cannot see these extra '0D', but you can see them in two cases:
1. Copy/paste from Nesicide to another editor
2. (Indeed) while debugging. 
While I have some play with C example and debugging it (looks really cool) I felt you should run 0D0D0Afixer in examples pack before they are packed somehow. 
I made source code linux/windows compatible but never compile or run in linux. Without parameters it scans all subfolders for problem and shows files with found problems. With single parameter 'fix' it will also fix it.

**Comment by christopherpow** [comment]
I'm going to claim success on this with the build that is currently being done/deployed. At least "works for me" level success. I've also added a few features I'd wanted to add for a long time, like being able to turn off the tabbed view and being able to close open items from the Open Items list in the project browser. So, good times.

**Comment by aa-dav** [comment]
Cool! I'll monitor it like always. If it will happen again I'll inform you.
