### ISSUE TITLE
Creating project from "CC65 C" template generates main.s with CRCRCRLF as newlines

### ISSUE THREAD

**Issue by aa-dav** [christopherpow/nesicide#64]
Windows 10, latest build, as always.
Create new project from template "Hello world - CC65 C" and close IDE (even without opening any files in editor). main.s will have triple CR + LF as new lines. This issue existed several builds ago, but I do not use C and do not mention it. But it can be related to last isssues somehow. Also you can run 0D0D0Afix twice to fix this file if it is damaged in archive already.
(I run several times existing projects but didn't see 0D0D0A problem yet with existing files)

**Comment by christopherpow** [comment]
I missed this one yesterday. It's fixed today. Building now.
