### ISSUE TITLE
Setting MMC5 register crashes or doesn't cause desired effects

### ISSUE THREAD

**Issue by rdrpenguin04** [christopherpow/nesicide#65]
I stumbled upon this IDE, and so I decided to try it out for one of my projects!

Problem: I use MMC5, and it seems the only way to get the linker to like me is to use banking mode 1, which splits the PRG into 2 chunks of 16K, with the $C000-$FFFF block being fixed and $8000-$BFFF being switchable. My first few instructions are this: (located at $E000)
```
sei
ldx #1
stx $5010
```
As soon as the STX hits, the program segfaults.

Any suggestions on how to fix this?

**Comment by christopherpow** [comment]
At present my MMC5 emulation is sub-par at best. I'm hoping to get back to it soon, though. Perhaps if you could share a small example project showing the problem precisely, I can figure it out and get a new build deployed ASAP. Submitting issues also helps me focus on what people need me to get done. Thanks.

**Comment by rdrpenguin04** [comment]
No prob! It's a private project, but I've invited you to it. Here's the commit: https://github.com/rdrpenguin04/The-Miner/tree/b408fe6a1b7f5a24f15f2a636b2e706c106e9ce9

We are beginning to employ a workaround where we use mode 0 but use it as if it were mode 1.

Once again, thank you for developing this! Without it, I probably wouldn't even be able to start NES development.

**Comment by rdrpenguin04** [comment]
And by mode 0, I mean mode 3. Clearly I don't do my research.

**Comment by christopherpow** [comment]
Ok I'll try to check it out today. Stay safe!

**Comment by rdrpenguin04** [comment]
Will do!

By the way, I've been catching many other editor crashes when I try to work on stuff. I'll debug those a bit and get back to you.

Have a great rest of your day!

**Comment by christopherpow** [comment]
I'm not sure why you're writing 0x01 to 0x5010. But if I add: 
ldx #$be
stx $5116
then I can step through the code properly. It seems my initialization of the PRG bank for A000-BFFF might not be correct. The above code sets it to the n-2th 8KB bank of PRG data.
I've not been able to find concrete evidence on what 8KB bank should be placed at A000 at init...but I'm willing to concede it'd probably be best to set it to n-2th. I'll commit a fix and have a build soon.

**Comment by christopherpow** [comment]
RE crashes: what platform?

**Comment by rdrpenguin04** [comment]
The reason I'm writing to $5010 is... oh shoot, I misread that number. I'll fix that.
Also, I added in the code in the latest version to set the correct bank. You're initializing it correctly to my knowledge.
The crashes are happening on Linux 64-bit (Linux Mint, based on Ubuntu Bionic). My computer is particularly overworked in terms of RAM and CPU, so definitely unusual conditions, but I'll try to fix it.
I will fix my code so I'm writing to the correct address, but I'm confused as to why writing to a bad address would cause a segfault. If anything, it should just put in a value for open bus reads.
Anyways, thank you for your help! I'll leave this issue open for you to close it when you feel it's fixed. You have a great IDE here, and I thank you for making it! You're supporting the NES development scene going forward, and I look forward to seeing how this develops!

**Comment by rdrpenguin04** [comment]
Note: The crashes usually happen either when switching to the emulator view or when stepping the emulator. The crashes I have seen are:
 * "Segmentation fault (core dumped)"
 * "free(): invalid pointer" (followed by "Aborted (core dumped)")
 * "\*\*\*stack smashing detected***: <unknown> terminated" (followed by "Aborted (core dumped)")
 * "corrupted size vs. prev_size" (followed by "Aborted (core dumped)")

**Comment by christopherpow** [comment]
Are you running the latest build from b4ff3db?
Can you run gdb on it and get a stack trace?
Also, I think I'll revert my MMC5 init change since it makes no difference in the games that don't work.

**Comment by christopherpow** [comment]
Also there's no crash (for me in OSX...I'll try Ubuntu) when writing to $5010. That is an actual register on the MMC5.

**Comment by rdrpenguin04** [comment]
I got the build yesterday, I'll download a new one next opportunity. I'll gdb on that one as well.
When writing to $5100, it doesn't look like the mapping properly updates. Looking in the debugger, the register says that it should be in 16KB banking mode, but the PRG-ROM map doesn't change, and trying to jump into that memory doesn't work.

**Comment by rdrpenguin04** [comment]
Also, where do you see that $5010 is an actual register? I'm looking at the NESDev page and I don't see it.

**Comment by christopherpow** [comment]
[005.txt](https://github.com/christopherpow/nesicide/files/4352054/005.txt)
I'm not sure where I got the bitfield defn's from for it...weird. I think I perhaps just assumed since it's DMC it must be similar to $4010.

**Comment by rdrpenguin04** [comment]
Huh. Anyway, I had no luck using gdb. The AppImage immediately spawns a new process and then exits, so the debugger loses track of it.

**Comment by christopherpow** [comment]
I see crashes in Ubuntu. I'll check it out. It might just be MMC5 nonsense...the C example project works OK.

**Comment by rdrpenguin04** [comment]
Do you think that you could fix switching the mode actually switching the PRG banks?

**Comment by christopherpow** [comment]
I'm working on that now. I didn't realize writing to $5100 changes them. :|

**Comment by rdrpenguin04** [comment]
I mean, I'd assume it would. There's a chance that the bank would need to be set again, but it seems like the hardware would be more likely to do it automatically. I don't have solid proof either way though.

**Comment by rdrpenguin04** [comment]
Check this for reference: https://github.com/TASVideos/BizHawk/blob/master/BizHawk.Emulation.Cores/Consoles/Nintendo/NES/Boards/ExROM.cs

NESHawk is an emulator made for accuracy, mainly because it's made for TASing. I'd recommend it as a reference any day.

**Comment by christopherpow** [comment]
Thanks for the reference. I've made some changes based on my interpretation of that. It works better, but still not for Just Breed or Uncharted Waters. There's a reason my MMC5 emulation status is yellow on my website. :)

**Comment by rdrpenguin04** [comment]
Sounds good! I'll maybe take a look at those games later, I'm not sure. Thank you for fixing that though!

**Comment by christopherpow** [comment]
I was able to get a backtrace from gdb on Ubuntu. Not sure what you did differently, but all I did was gdb ./nesicide-c79728b-x86_64.AppImage then run.

**Comment by christopherpow** [comment]
Thread 1 "AppRun" received signal SIGSEGV, Segmentation fault.
0x00000000004b3405 in RENDERCPUCODEDATALOGGER() ()
(gdb) 
(gdb) 
(gdb) 
(gdb) 
(gdb) 
(gdb) 
(gdb) 
(gdb) 
(gdb) bt
#0  0x00000000004b3405 in RENDERCPUCODEDATALOGGER() ()
#1  0x00000000004b47bf in DebuggerUpdateWorker::updateDebuggers() ()
#2  0x00007ffff5a887c9 in QMetaObject::activate(QObject*, int, int, void**) () from /tmp/.mount_nesiciqlz1Am/lib/libQt5Core.so.5
#3  0x00007ffff5a89809 in QObject::event(QEvent*) () from /tmp/.mount_nesiciqlz1Am/lib/libQt5Core.so.5
#4  0x00007ffff662858c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /tmp/.mount_nesiciqlz1Am/lib/libQt5Widgets.so.5
#5  0x00007ffff662fed7 in QApplication::notify(QObject*, QEvent*) () from /tmp/.mount_nesiciqlz1Am/lib/libQt5Widgets.so.5
#6  0x00007ffff5a5b6b8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /tmp/.mount_nesiciqlz1Am/lib/libQt5Core.so.5
#7  0x00007ffff5a5e7eb in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /tmp/.mount_nesiciqlz1Am/lib/libQt5Core.so.5
#8  0x00007ffff5ab32b3 in ?? () from /tmp/.mount_nesiciqlz1Am/lib/libQt5Core.so.5
#9  0x00007ffff33b0d5e in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#10 0x00007ffff33b0ff8 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#11 0x00007ffff33b108c in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#12 0x00007ffff5ab28bf in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /tmp/.mount_nesiciqlz1Am/lib/libQt5Core.so.5
#13 0x00007fffeb170881 in ?? () from /tmp/.mount_nesiciqlz1Am/plugins/platforms/../../lib/libQt5XcbQpa.so.5
#14 0x00007ffff5a5993a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /tmp/.mount_nesiciqlz1Am/lib/libQt5Core.so.5
#15 0x00007ffff5a62ba4 in QCoreApplication::exec() () from /tmp/.mount_nesiciqlz1Am/lib/libQt5Core.so.5
#16 0x00000000004433c1 in main ()
(gdb)

**Comment by christopherpow** [comment]
I'll dig into that...

**Comment by christopherpow** [comment]
Had a bit of a setback and am upgrading my VM to Ubuntu 19. :|

**Comment by christopherpow** [comment]
Ok I'm back. I am (hopefully) at root cause on this and working a fix. Sorry for the delay.

**Comment by rdrpenguin04** [comment]
No prob! Looking forward to working on NES games again!

**Comment by christopherpow** [comment]
Try the latest build. It isn't perfect, I still need to work on a smoother project open/close transition, but it seems to survive on my end without crashing. If you continue to have MMC5 issues (I know you will, as I've already admitted my MMC5 is suboptimal), just open new issues. Thanks!
