### ISSUE TITLE
Tips for OSX compilation?

### ISSUE THREAD

**Issue by michaeldauria** [christopherpow/nesicide#8]
Just tried to clone and make and i am seeing this:

```
make -C apps/nes-emulator
make[1]: *** No rule to make target `Resources/controller.icns', needed by `release/nes-emulator.app/Contents/Resources/controller.icns'.  Stop.
make: *** [apps/nes-emulator/nes-emulator] Error 2
```

**Comment by christopherpow** [comment]
If you download the OSX-updated deps package that has the WINE headers in it now.

It is here:
https://sites.google.com/site/nesicideproject/documents/deps.tar.bz2?attredirects=0&d=1
